### ISSUE TITLE
Check for 0 value cart

### ISSUE THREAD

**Issue by MYSTERYouse** [graphpaperpress/Sell-Media#614] opened 2014-05-13 16:37 UTC
If the cart has zero value, do not send to payment gateway. 

In case you use 100% discount with the use of discount plugin you can get to a 0 value. Maybe add a check before sending to the payment gateway if value 0, automatically approve purchase.

**Comment by mintcanary** [comment] 2015-05-08 20:24
+1

Also, I'm finding that attempting to check out with a cart total of zero is creating an order of £1 in PayPal.

**Comment by mintcanary** [comment] 2015-05-23 07:53
Another scenario is that you create a license with -100% "markup".

**Comment by mintcanary** [comment] 2015-06-12 20:39
Did this not make it into 2.0.4 (not mentioned in the change log)?

**Comment by thadallender** [comment] 2016-02-10 19:26
Version 2.1 (available this week) has this feature. 7cc31e7b6d736aa318bf5aa1811068915b2868dc

**Comment by MYSTERYouse** [comment] 2016-02-26 11:20
I was just testing this and it still send the user to paypal gateway. Is there anything else that needs to be done, 
Scenario 1 - Latest free download extension is installed, box for free item ticked - free download works
Scenario 2 - All up to date, pricing set per item, discount code 100%, user gets send to PayPal

It means only the first scenario has been fixed - right?

**Comment by thadallender** [comment] 2016-02-26 13:36
In the latest version of Sell Media, all you have to do is assign a price
of $0 to any item and the Buy button changes into a Download button. It
shouldn't be adding it to the cart at all.

**Comment by MYSTERYouse** [comment] 2016-02-26 17:18
Have a look here, I used a clean blog with nothing else just sell media and stock photography theme http://fotosport.mysteryouse.com/ - only item there has a 0 price.

**Comment by thadallender** [comment] 2016-02-26 18:04
Ah, yes I can also reproduce this locally. We added this feature a few weeks back. It looks like the new Quick View changes reverted the changes. This issue will be fixed early next week.

Thanks for reporting it.

**Comment by thadallender** [comment] 2016-05-08 14:48
Fixed in version 2.1.6 or above.

**Closed by thadallender** 2016-05-08 14:48 UTC
Labels: feature-request
