### ISSUE TITLE
Error on Fresh setup [front end].

### ISSUE THREAD

**Issue by codearryaas** [graphpaperpress/Sell-Media#739] opened 2016-01-12 05:56 UTC
There are errors on fresh setup of Sell Media front end. Please check attachment.
![issue-10](https://cloud.githubusercontent.com/assets/16424358/12255951/52ba07c0-b921-11e5-9d8c-f23dfdbd9342.png)

**Comment by thadallender** [comment] 2016-01-12 09:19
I don't see the attachment. Please resend.

**Comment by codearryaas** [comment] 2016-01-12 09:48
Please check link below:
https://cloud.githubusercontent.com/assets/16424358/12260078/bb81221e-b941-11e5-90dc-707d31a6f0fa.png

**Comment by thadallender** [comment] 2016-01-12 15:26
I'm not seeing these notices issues at all. Can you pull the latest version from GitHub and see if it fixes your issue? If it does, please provide the exact steps to reproduce these issues.

**Comment by thadallender** [comment] 2016-02-08 21:05
Closing this since neither one of use can replicate it. Please reopen if you see it again and answer these questions:

I DID...
I SAW...
I EXPECTED...

**Closed by thadallender** 2016-02-08 21:05 UTC
